# Generated by Django 3.1.6 on 2022-04-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'addressdb',
            },
        ),
        migrations.CreateModel(
            name='SpecialityDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=10)),
                ('speciality', models.CharField(default='None', max_length=20)),
            ],
            options={
                'db_table': 'specialitydb',
            },
        ),
    ]
