# Generated by Django 3.1.6 on 2022-04-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_postdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDb',
        ),
    ]
