# Generated by Django 3.1.6 on 2022-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_postdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='doc_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
