# Generated by Django 3.1.6 on 2022-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_postdb_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='doc_name',
            field=models.CharField(max_length=100),
        ),
    ]
