# Generated by Django 3.1.6 on 2022-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20220426_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdb',
            name='day',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='addressdb',
            name='fromtime',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='addressdb',
            name='totime',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
