# Generated by Django 3.2.7 on 2022-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0007_auto_20220326_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
