# Generated by Django 3.1.6 on 2022-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0011_auto_20220426_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ph_no',
            field=models.CharField(default='None', max_length=11),
        ),
        migrations.AddField(
            model_name='patient',
            name='ph_no',
            field=models.CharField(default='None', max_length=11),
        ),
    ]
