# Generated by Django 3.1.6 on 2022-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0012_auto_20220515_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=10)),
                ('pat_id', models.CharField(max_length=10)),
                ('rate_1', models.CharField(max_length=10)),
                ('rate_2', models.CharField(max_length=10)),
                ('rate_3', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
