# Generated by Django 3.1.6 on 2022-05-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0013_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rate_2',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rate_3',
        ),
    ]
