# Generated by Django 3.1.6 on 2022-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0014_auto_20220516_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='speciality',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
